import { useState } from 'react'

function toWebp(url: string): string {
  return url.replace(/\.(jpe?g|png)(\?.*)?$/i, '.webp$2')
}

interface Props extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string
  onLoadError?: () => void
}

/**
 * Renders the WebP sibling of `src` first (generated by erp_sync for every
 * product photo — ~90% smaller than the original jpg/png), falling back to
 * the original via onError if that specific file is somehow missing.
 * <picture>/<source> doesn't retry on a 404, so the fallback has to be a
 * plain <img> with a JS-driven src swap instead.
 */
export default function SmartImage({ src, onLoadError, onError, ...rest }: Props) {
  const [triedFallback, setTriedFallback] = useState(false)
  const webpSrc = toWebp(src)
  const usingWebp = webpSrc !== src && !triedFallback

  return (
    <img
      {...rest}
      src={usingWebp ? webpSrc : src}
      onError={(e) => {
        if (usingWebp) {
          setTriedFallback(true)
          return
        }
        onLoadError?.()
        onError?.(e)
      }}
    />
  )
}
